[custom]
;======================================================================================================================================

;《ACL4SSR规则》

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

;ruleset=乙组,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Telegram.list
;ruleset=乙组,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
;ruleset=乙组,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list

;ruleset=丙组,https://raw.githubusercontent.com/Github989898/Github989898/main/extra.list

;ruleset=🚧 自我定义,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
;ruleset=🚧 自我定义,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
;ruleset=🚧 自我定义,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitch.list


ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN

ruleset=🚀 节点选择,[]FINAL

;======================================================================================================================================

;《节点策略组》

custom_proxy_group=🚀 节点选择`select`[]甲组`[]泡泡dog`[]顶级机场
;custom_proxy_group=🚧 自我定义`select`[]乙组`[]甲组`[]丙组

custom_proxy_group=甲组`fallback`[]顶级机场`[]泡泡dog`http://www.apple.com/library/test/success.html`99
custom_proxy_group=泡泡dog`fallback`(美国洛杉矶2号|迪拜)`http://www.apple.com/library/test/success.html`129
custom_proxy_group=顶级机场`fallback`(日本东京3号|法兰克福|迪拜)`http://www.apple.com/library/test/success.html`149

custom_proxy_group=🎯 全球直连`select`[]DIRECT
;custom_proxy_group=IP`select`(.*)


;======================================================================================================================================
;《节点：重命名、包含、排除》

add_emoji=true
include_remarks=(日本东京3号|美国洛杉矶2号|法兰克福|迪拜)
exclude_remarks=(剩余|距离|去除|套餐到期|美国凤凰城$|gpt|0.1)

;======================================================================================================================================

;《备忘录》
;手动选择`select`。自动选择`url-test`。故障转移`fallback`。负载均衡`load-balance`。链式代理`relay`。
;http://www.gstatic.com/generate_204`300,,50
;http://www.apple.com/library/test/success.html`90,,50
;======================================================================================================================================
enable_rule_generator=true
overwrite_original_rules=true
